
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'DCF1E6C69F9106E0D00E0826C8F84A0D'
    
_lr_action_items = {'WIRE':([4,5,10,12,13,23,27,29,31,35,42,43,44,47,],[-6,11,-14,-5,11,-13,-9,-7,-11,-16,-10,-8,-12,-15,]),'DEFPARAM':([63,],[66,]),')':([33,34,46,55,56,60,64,67,],[45,-4,-3,-23,59,-22,67,-24,]),'(':([9,41,58,],[20,51,62,]),'MODULE':([0,],[2,]),'.':([51,55,56,60,67,68,],[54,-23,54,-22,-24,69,]),'VECTOR':([6,7,8,11,],[15,17,19,22,]),'HEX_NUMBER':([71,],[72,]),'ENDMODULE':([39,40,50,61,],[-26,49,-25,-27,]),'OUTPUT':([1,4,5,12,27,29,31,42,43,44,52,],[6,-6,6,-5,-9,-7,-11,-10,-8,-12,-2,]),'INPUT':([1,4,5,12,27,29,31,42,43,44,52,],[7,-6,7,-5,-9,-7,-11,-10,-8,-12,-2,]),';':([14,16,18,21,28,30,32,36,45,57,59,72,],[27,29,31,35,42,43,44,47,52,61,63,73,]),'IDENTIFIER':([2,6,7,8,10,11,13,15,17,19,20,22,23,24,25,26,33,34,35,37,38,46,47,53,54,62,63,65,66,69,73,],[9,14,16,18,-14,21,26,28,30,32,34,36,-13,-18,26,41,46,-4,-16,-17,48,-3,-15,57,58,64,-19,-20,68,70,-21,]),'=':([48,70,],[53,71,]),'ASSIGN':([24,25,37,39,40,50,61,63,65,73,],[-18,38,-17,-26,38,-25,-27,-19,-20,-21,]),'INOUT':([1,4,5,12,27,29,31,42,43,44,52,],[8,-6,8,-5,-9,-7,-11,-10,-8,-12,-2,]),'$end':([3,49,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'signal_decl':([5,13,],[10,23,]),'primitive':([13,25,],[24,37,]),'module_decl':([0,],[1,]),'port_decl':([1,5,],[4,12,]),'primitive_port':([51,56,],[55,60,]),'primitive_list':([13,],[25,]),'port_decl_list':([1,],[5,]),'defparam':([63,],[65,]),'signal_decl_list':([5,],[13,]),'vm_file':([0,],[3,]),'pipo_list':([20,],[33,]),'assign_stm':([25,40,],[39,50,]),'assign_stm_list':([25,],[40,]),'primitive_port_list':([51,],[56,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> vm_file","S'",1,None,None,None),
  ('vm_file -> module_decl port_decl_list signal_decl_list primitive_list assign_stm_list ENDMODULE','vm_file',6,'p_vmfile',u'netlist_parser.py',132),
  ('module_decl -> MODULE IDENTIFIER ( pipo_list ) ;','module_decl',6,'p_module_decl',u'netlist_parser.py',136),
  ('pipo_list -> pipo_list IDENTIFIER','pipo_list',2,'p_pipo_list',u'netlist_parser.py',140),
  ('pipo_list -> IDENTIFIER','pipo_list',1,'p_pipo_list',u'netlist_parser.py',141),
  ('port_decl_list -> port_decl_list port_decl','port_decl_list',2,'p_port_decl',u'netlist_parser.py',146),
  ('port_decl_list -> port_decl','port_decl_list',1,'p_port_decl',u'netlist_parser.py',147),
  ('port_decl -> INPUT IDENTIFIER ;','port_decl',3,'p_port_decl',u'netlist_parser.py',148),
  ('port_decl -> INPUT VECTOR IDENTIFIER ;','port_decl',4,'p_port_decl',u'netlist_parser.py',149),
  ('port_decl -> OUTPUT IDENTIFIER ;','port_decl',3,'p_port_decl',u'netlist_parser.py',150),
  ('port_decl -> OUTPUT VECTOR IDENTIFIER ;','port_decl',4,'p_port_decl',u'netlist_parser.py',151),
  ('port_decl -> INOUT IDENTIFIER ;','port_decl',3,'p_port_decl',u'netlist_parser.py',152),
  ('port_decl -> INOUT VECTOR IDENTIFIER ;','port_decl',4,'p_port_decl',u'netlist_parser.py',153),
  ('signal_decl_list -> signal_decl_list signal_decl','signal_decl_list',2,'p_signal_decl_list',u'netlist_parser.py',157),
  ('signal_decl_list -> signal_decl','signal_decl_list',1,'p_signal_decl_list',u'netlist_parser.py',158),
  ('signal_decl -> WIRE VECTOR IDENTIFIER ;','signal_decl',4,'p_signal_decl_list',u'netlist_parser.py',159),
  ('signal_decl -> WIRE IDENTIFIER ;','signal_decl',3,'p_signal_decl_list',u'netlist_parser.py',160),
  ('primitive_list -> primitive_list primitive','primitive_list',2,'p_primitive_list',u'netlist_parser.py',164),
  ('primitive_list -> primitive','primitive_list',1,'p_primitive_list',u'netlist_parser.py',165),
  ('primitive -> IDENTIFIER IDENTIFIER ( primitive_port_list ) ;','primitive',6,'p_primitive_list',u'netlist_parser.py',166),
  ('primitive -> IDENTIFIER IDENTIFIER ( primitive_port_list ) ; defparam','primitive',7,'p_primitive_list',u'netlist_parser.py',167),
  ('defparam -> DEFPARAM IDENTIFIER . IDENTIFIER = HEX_NUMBER ;','defparam',7,'p_primitive_list',u'netlist_parser.py',168),
  ('primitive_port_list -> primitive_port_list primitive_port','primitive_port_list',2,'p_primitive_port_list',u'netlist_parser.py',172),
  ('primitive_port_list -> primitive_port','primitive_port_list',1,'p_primitive_port_list',u'netlist_parser.py',173),
  ('primitive_port -> . IDENTIFIER ( IDENTIFIER )','primitive_port',5,'p_primitive_port_list',u'netlist_parser.py',174),
  ('assign_stm_list -> assign_stm_list assign_stm','assign_stm_list',2,'p_assign_stm_list',u'netlist_parser.py',178),
  ('assign_stm_list -> assign_stm','assign_stm_list',1,'p_assign_stm_list',u'netlist_parser.py',179),
  ('assign_stm -> ASSIGN IDENTIFIER = IDENTIFIER ;','assign_stm',5,'p_assign_stm_list',u'netlist_parser.py',180),
]
